baseURL: 'https://hackkosice.com/'
languageCode: en-us
title: Hack Kosice
theme: orbitor-hugo
summaryLength: '10'
paginate: 4
outputs:
  home: ["HTML", "AMP", "RSS", "JSON"]
timeout: 120s
markup:
  goldmark:
    renderer:
      unsafe: true
params:
  plugins:
    css:
      - URL: plugins/bootstrap/css/bootstrap.min.css
      - URL: plugins/themify/css/themify-icons.css
      #- URL: plugins/magnific-popup/dist/magnific-popup.css
      #- URL: plugins/modal-video/modal-video.css
      #- URL: plugins/animate-css/animate.css
      - URL: plugins/slick-carousel/slick/slick.css
        defer: true
      - URL: plugins/slick-carousel/slick/slick-theme.css
        defer: true
    js:
      - URL: plugins/jQuery/jquery.min.js
      #- URL: plugins/bootstrap/js/popper.js
      - URL: plugins/bootstrap/js/bootstrap.min.js
      #- URL: plugins/magnific-popup/dist/jquery.magnific-popup.min.js
      - URL: plugins/slick-carousel/slick/slick.min.js
      - URL: plugins/counterup/jquery.waypoints.min.js
      - URL: plugins/counterup/jquery.counterup.min.js
      #- URL: plugins/modal-video/modal-video.js
      #- URL: plugins/search/fuse.min.js
      #- URL: plugins/search/mark.js
      #- URL: plugins/search/search.js
      #- URL: plugins/google-map/map.js
      - URL: plugins/js-cookie/js.cookie.min.js
  logo: images/logo.svg
  logoAlt: images/logo.svg
  home: Home
  description: 250 Hackers. 24 Hours. 1 Spirit.
  images:
    - images/bg/background.jpg
  author: Hack Kosice
  cookie: true
  expireDay: 14
  gmapAPI: >-
    https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places
  mapLatitude: '51.5223477'
  mapLongitude: '-0.1622023'
  mapMarker: images/marker.png
  googleAnalitycsID: G-ZGVQV42MKT
  copyright: '&copy; Copyright Hack Kosice 2020'
  preloader:
    enable: true
  navBtn:
    enable: true
    label: Contact
    link: contact
  footer:
    about:
      title: Hack Kosice
      content: >-
        Our motivation is to bring the great experience of international hackathons closer to our home, Slovakia, and as a result, create
        something extraordinary.
  contact:
    #mobile: +23-345-67890
    email: contact@hackkosice.com
    text: |
      We are friendly.<br>We also speak Slovak.
    location: 'Kosice, Slovakia'
    location_link: https://goo.gl/maps/EZqNzAveuW5iPss86
  social:
    - icon: ti-facebook
      link: 'https://www.facebook.com/hackkosice/'
    - icon: ti-twitter-alt
      link: 'https://twitter.com/HackKosice'
    - icon: ti-instagram
      link: 'https://www.instagram.com/hackkosice/'
  postShare:
    - icon: ti-facebook
      link: 'https://www.facebook.com/hackkosice/'
    - icon: ti-twitter-alt
      link: 'https://twitter.com/HackKosice'
    - icon: ti-instagram
      link: 'https://www.facebook.com/hackkosice/'
menu:
  main:
    - name: Hackathon 2020
      identifier: hk20
      weight: 30
    - name: Activities
      identifier: opportunities
      weight: 50
  #footer1:
    #- name: Page
    #  URL: page
    #  weight: 1
  footer2:
    - name: MLH Code of Conduct
      URL: https://static.mlh.io/docs/mlh-code-of-conduct.pdf
      weight: 30
    - name: MLH Privacy Policy
      URL: https://mlh.io/privacy
      weight: 40
    - name: MLH Contest T&C
      URL: https://github.com/MLH/mlh-policies/blob/master/prize-terms-and-conditions/contest-terms.md
      weight: 50
