version: 2.1
orbs:
  hugo: circleci/hugo@0.5.2
jobs:
  deploy_dev:
    docker:
      - image: cibuilds/base
    steps:
      #- attach_workspace:
      #    at: workspace
      - add_ssh_keys
      - run:
          name: Deploy at server
          command: |
            echo 'hackkosice.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBCHgOExXpEGEvZ1Usofy87wMdTgOwKtEwoHft6q2MTuup25f4bmgj3SyB5/sjpySSs0ti7Vg60EtzRMMvRSXbv4=' >> ~/.ssh/known_hosts
            ssh -v hackkosice@hackkosice.com "~/dev.hackkosice.com/deploy.sh"
workflows:
  main:
    jobs:
      - hugo/build:
          version: '0.73'
          html-proofer: false
          hugo-extra-flags: -DF
      - deploy_dev:
          filters:
            branches:
              only: master
          requires:
            - hugo/build
