version: 2.1
orbs:
  hugo: circleci/hugo@0.5.2
jobs:
  deploy:
    docker:
      - image: cibuilds/base
    steps:
      #- attach_workspace:
      #    at: workspace
      - run: ssh -v hackkosice@hackkosice.com "~/dev.hackkosice.com/deploy.sh"
workflows:
  main:
    jobs:
      - hugo/build:
          version: '0.73'
          html-proofer: false
          hugo-extra-flags: -DF
      - deploy:
          filters:
            branches:
              only: production
          requires:
            - hugo/build
