version: 2.1
orbs:
  hugo: circleci/hugo@0.5.2
  firebase-deploy: azdevs/firebase-deploy@1.0.0
parameters:
  hugo-version:
    type: string
    default: '0.73'
  deploy-branch:
    type: string
    default: 'master'
jobs:
  build:
    description: Build the site with Hugo.
    executor:
      name: hugo/cibuilds
      tag: << pipeline.parameters.hugo-version >>
    parameters:
      html-proofer:
        default: true
        description: Whether or not to test the outputted HTML with HTML Proofer.
        type: boolean
    steps:
      - checkout
      - hugo/hugo-build:
          extra-flags: -DF
      - when:
          condition: << parameters.html-proofer >>
          steps:
            - hugo/html-proofer:
                path: ./public
  deploy_dev:
    parameters:
      baseurl:
        type: string
    docker:
      - image: cibuilds/base
    steps:
      - add_ssh_keys
      - run:
          name: Deploy at server
          command: |
            echo 'hackkosice.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBCHgOExXpEGEvZ1Usofy87wMdTgOwKtEwoHft6q2MTuup25f4bmgj3SyB5/sjpySSs0ti7Vg60EtzRMMvRSXbv4=' >> ~/.ssh/known_hosts
            ssh hackkosice@hackkosice.com '
              cd dev.hackkosice.com/repository
              git checkout << pipeline.parameters.deploy-branch >>
              git pull
              rm -r public
              hugo --baseURL="<< parameters.baseurl >>"
              cp -r public/* ../public_html'
  deploy_firebase:
    parameters:
      baseurl:
        type: string
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - hugo/hugo-build:
          extra-flags: -DF --baseURL="<< parameters.baseurl >>"
      - firebase-deploy/deploy:
          token: $FIREBASE_TOKEN
workflows:
  main:
    jobs:
      - build:
          html-proofer: false
      - deploy_dev:
          baseurl: 'https://dev.hackkosice.com/'
          filters:
            branches:
              only: << pipeline.parameters.deploy-branch >>
          requires:
            - build
      - deploy_firebase:
          baseurl: 'https://fire.hackkosice.com/'
          filters:
            branches:
              only: << pipeline.parameters.deploy-branch >>
          requires:
            - build
