version: 2.1
orbs:
  hugo: circleci/hugo@0.5.2
parameters:
  deploy-branch:
    type: string
    default: 'master'
jobs:
  build:
    executor:
      name: hugo/cibuilds
      tag: '0.79'
    parameters:
      html-proofer:
        default: true
        description: Whether or not to test the outputted HTML with HTML Proofer.
        type: boolean
    steps:
      - checkout
      - hugo/hugo-build:
          extra-flags: -DF
      - when:
          condition: << parameters.html-proofer >>
          steps:
            - hugo/html-proofer:
                path: ./public
  deploy_dev:
    parameters:
      baseurl:
        type: string
    docker:
      - image: cibuilds/base
    steps:
      - add_ssh_keys
      - run:
          name: Deploy at server
          command: |
            echo 'hackkosice.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBCHgOExXpEGEvZ1Usofy87wMdTgOwKtEwoHft6q2MTuup25f4bmgj3SyB5/sjpySSs0ti7Vg60EtzRMMvRSXbv4=' >> ~/.ssh/known_hosts
            ssh hackkosice@hackkosice.com '
              cd dev.hackkosice.com/repository
              git checkout << pipeline.parameters.deploy-branch >>
              git pull
              rm -r public
              hugo --baseURL="<< parameters.baseurl >>" -DF
              cp -r public/* ../public_html'
  deploy_firebase:
    parameters:
      baseurl:
        type: string
      html-proofer:
        default: false
        description: Whether or not to test the outputted HTML with HTML Proofer.
        type: boolean
    docker:
      - image: hackkosice/hugo:0.79.0
    environment:
      TZ: "Europe/Bratislava"
      NODE_ENV: "development"
    steps:
      - checkout
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json
            - npm-deps-v1-{{ checksum "package-lock.json" }}-{{ checksum "functions/package-lock.json" }}
            # Fallback cache to be used
            - npm-deps-v1-
      - run:
          name: Install Dependencies
          command: npm install --unsafe-perm
      - save_cache:
          key: npm-deps-v1-{{ checksum "package-lock.json" }}-{{ checksum "functions/package-lock.json" }}
          paths:
            - node_modules
            - functions/node_modules
      - hugo/hugo-build:
          extra-flags: --baseURL="<< parameters.baseurl >>"
      - when:
          condition: << parameters.html-proofer >>
          steps:
            - hugo/html-proofer:
                path: ./public
      - run:
          name: Deploy to Firebase
          command: |
            npm install --prefix=./firebase-deploy firebase-tools
            ./firebase-deploy/node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN --only hosting
workflows:
  main:
    jobs:
      - deploy_firebase:
          baseurl: 'https://hackkosice.com/'
          filters:
            branches:
              only: << pipeline.parameters.deploy-branch >>
